name: CI

on:
  workflow_dispatch:
  push:
  schedule:
    # 详细cron设置请访问https://crontab.guru
    # 每天9点10分签到完所有账号，格式：'10 9 * * *'
    - cron: "18 20 * * *"

jobs:
  convert:
    name: convert
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: convert subscribe
      run: |
        mkdir -p output
        sed -i 's|~|${{ secrets.SUB_URL }}|g' config/generate.ini
        docker run --rm \
          -v ${GITHUB_WORKSPACE}/config/:/base/ \
          -v ${GITHUB_WORKSPACE}/output/:/base/output/ \
          tindy2013/subconverter:latest \
            subconverter -g
    - name: fix surfboard 订阅链
      run: |
        sed -i "1s|https\?[^ ]\+\s|${{ secrets.SB_CONF }} |g" output/surfboard.conf
    - name: Setup Ossutil
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: ${{ secrets.EP }}
        access-key-id: ${{ secrets.AKID }}
        access-key-secret: ${{ secrets.AKS }}
    - run: ossutil cp -rf output/ oss://${{ secrets.BK }}/ --meta="Content-Type:text/plain; charset=utf-8"
